# deploy specific image tag to test

parameters:
- name: IMAGE_TAG
  displayName: IMAGE_TAG
  type: string

trigger: none
#trigger:
#  branches:
#    include:
#      - master
#  paths:
#    exclude:
#      - azure-pipelines.yml
#      - azure-pipelines-deploy2.yml

variables:
  vmImageName: 'ubuntu-latest'
  tag: ${{ parameters.IMAGE_TAG }}
  containerRegistry: 'heckelregistry.azurecr.io'
  imageRepository: 'jheckel123mavenwebapp'
  imagePullSecret: 'heckelregistry-auth'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Publish
    displayName: Publish Manifests
    pool:
      vmImage: $(vmImageName)
    steps:
    # this is needed so they are available during AKS deployment
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'aitsAks'
              namespace: 'test'
              secretType: 'dockerRegistry'
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'heckelRegistry'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'aitsAks'
              namespace: 'test'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

