apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: jheckel123mavenwebapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jheckel123mavenwebapp 
    spec:
      containers:
        - name: jheckel123mavenwebapp 
          image: heckelregistry.azurecr.io/jheckel123mavenwebapp
          ports:
          - containerPort: 8080
